config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations',  omniauth_callbacks: 'users/omniauth_callbacks'  }

  resources :users_admin, controller: 'users'

  resources :comptes do 
    get :balance
  end
  
  get 'moncompte/index'
  get 'moncompte/releve_compte'
  get 'moncompte/factures'
  get 'moncompte/absences'
  get 'moncompte/enfants'
  get 'moncompte/reservations'
  get 'moncompte/contacts'

  resources :factures do
    collection do
      post :action
    end
  end

  resources :enfants do
    collection do
      post :action
      post :action_execute
    end
  end

  resources :reservations, except: %i[ show create update ] do
    collection do
      post :action
      post :create_visiteur
    end
  end

  resources :prestations do
    collection do
      post :action
    end
  end
  resources :tarifs, except: %i[ index ]
  resources :absences
  resources :tarif_types, except: %i[ index show ]
  resources :prestation_types, except: %i[ index show ]
  resources :structures, except: %i[ index new create ]
  resources :organisations do
    member do
      get :suppression_organisation
      post :suppression_organisation_do
    end
  end
  resources :paiements
  resources :facture_messages
  resources :messages do
    member do
      get :traiter
      get :archiver
    end
  end
  resources :vacances, except: %i[ index ]
  resources :mail_logs, only: %i[ index show ]
  resources :pointages, only: %i[ index edit update ] do
    collection do
      post :action
    end
  end

  namespace :admin do
    get :index
    get :ajout_prestations
    get :ajout_factures
    get :tarifs
    get :audit
    get :import
    get :exemple_fichier_import_xls
    get :envoyer_factures
    get :mode_demonstration
    get :dashboard
    get :stats

    post :ajout_prestations_do
    post :ajout_factures_do
    post :import_do
    post :envoyer_factures_do
  end

  controller :pages do
    get :accueil, to: 'pages#home'
    get :guide, to: 'pages#guide'
    get :actualites, to: 'pages#actualites'
    get :confidentialite, to: 'pages#confidentialite'
    post :conditions_generales_de_vente, to: 'pages#conditions_generales_de_vente'
  end

  root 'pages#accueil'

end

app/views/admin/_audit.html.erb
<tr>
    <td><%= l(audit.created_at, format: :short) %></td>
    <td><%= audit.try(:user).try(:email) %></td>
    <td><%= audit.auditable_type %></td>
    <td style="text-align: right;"><%= audit.auditable_id %></td>
    <td><%= audit.action.humanize %></td>
    <td><%= sanitize prettify(audit).join('<br>') %></td>
</tr>

app/views/admin/ajout_factures.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light"><%= fa_icon 'calendar-day' %> Facturation des prestations</h2>
</div>

<p>
  <h4>Lance la création de factures à partir des prestations consommées</h4>
</p>
<br />

<%= bootstrap_form_with(url: 'ajout_factures_do', local: true) do |form| %>
  <div class="col-sm-4">
    <%= form.date_select :date, discard_day: true, label: "Mois", default: -1.month.from_now %>
    <%= form.select :compte_id, options_from_collection_for_select(current_user.organisation.comptes, :id, :nom, params[:compte_id]), { include_blank: 'Tous' } %>
    <%= form.check_box :enregistrer, { custom: :switch, label: "Enregistrer les factures *" } %> 
    <small>
        * Off = Visualisation de contrôle. Ne fait rien de définitif.<br>
        Aucune facture ne sera crée.
    </small> 
  </div>
  <br>
  <%= form.submit "Lancer", class: "btn btn-outline-success", 'data-turbo': false %>
<% end %>

app/views/admin/ajout_factures_do.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light"><%= fa_icon 'calendar-day' %> Facturation des prestations</h2>
</div>

<pre>
  <%= simple_format(@stdout_stream) %>
</pre>

app/views/admin/ajout_prestations.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light"><%= fa_icon 'calendar-day' %> Comptabilisation des prestations</h2>
</div>

<p>
    <h4>Lancer la routine journalière de comptabilisation des prestations consommées</h4>
    <small>
      Cette fonction balaye l'ensemble des réservations prévues pour une date 
      et crée les lignes 'prestations' adéquates (si les paramètres concordes; jour de la semaine, Scolaire/HorsScolaire, absences...).
      Notez que cette routine est lancée chaque matin, automatiquement, pour comptabiliser les prestations effectuées la veille.  
    </small>
</p>
<br />

<%= bootstrap_form_with(url: 'ajout_prestations_do') do |form| %>
    <div class="col-sm-3">
      <%= form.date_field :date %>
    </div>
    <br>
    <%= form.check_box :enregistrer, {custom: :switch, label: "Enregistrer les changements ? (Décoché = Visualisation seulement. Ne fait rien de définitif :)"} %>  
    <br /><br />
    <%= form.submit "Lancer", class: "btn btn-outline-success", 'data-turbo': false %>
<% end %>

app/views/admin/ajout_prestations_do.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light"><%= fa_icon 'calendar-day' %> Comptabilisation des prestations consommées</h2>
</div>

<pre>
  <%= simple_format(@stdout_stream) %>
</pre>

app/views/admin/audit.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light"><%= fa_icon 'search' %> Audit des modifications</h2>
</div>

<%= bootstrap_form_tag url: admin_audit_path, method: :get do |f| %>
  <div class="row">
    <div class="col-sm-2"><%= f.date_field :date, value: params[:date], onchange: "this.form.submit()" %></div>
    <div class="col-sm-3"><%= f.select :user_id, options_from_collection_for_select(@users, 'id', 'email', params[:user_id]), { include_blank: true, label: "Utilisateur" }, { class: "selectpicker", onchange: "this.form.submit()" } %></div>
    <div class="col-sm-2"><%= f.select :type, options_for_select(@types, params[:type]), { include_blank: true, label: "Type" }, { class: "selectpicker", onchange: "this.form.submit()" } %></div>
  </div>
<% end %>

<div class="table-responsive">
  <table class="table table-bordered table-hover table-sm">
      <thead>
          <tr>
              <th>Date</th>
              <th>Utilisateur</th>            
              <th>Type</th>
              <th>id</th>
              <th>Action</th>
              <th>Modifications</th>
          </tr>
      </thead>
      <%= render partial: 'audit', collection: @audits.includes(:user) %>
  </table>
</div>

<%= page_entries_info @audits, entry_name: 'audit' %>
<%= paginate @audits, theme: 'twitter-bootstrap-4' %>

app/views/admin/dashboard.html.erb
<div class="pb-2 my-4 border-bottom">
  <h2 class="fw-light"><%= fa_icon 'tachometer-alt', class: 'text-primary' %> Stats / Tableau de bord</h2>
</div>

<div class="row mt-4">
  <div class="col px-5 mx-3">
    <p>Nombre de Comptes : <span class="float-end"><%= @organisation.comptes.count %></span></p>
    <p>Nombre d'Enfants : <span class="float-end"><%= nbr_enfants = @organisation.enfants.count %></span></p>
    <p>Nombre de Classes : <span class="float-end"><%= nbr_classes = @organisation.classrooms.count %></span></p>
    
    <% if nbr_classes > 0 %>
      <p>Nombre d'Enfants par Classe : <span class="float-end"><%= nbr_enfants / nbr_classes %></span></p>
    <% end %>
  </div>

  <div class="col px-5 mx-3">
    <p>Nombre de Réservations : <span class="float-end"><%= number_with_delimiter(@organisation.reservations.count, delimiter: " ") %></span></p>
    <p>Nombre de Prestations : <span class="float-end"><%= number_with_delimiter(@organisation.prestations.count, delimiter: " ") %></span></p>
    <% if @organisation.en_dépassement_plan_gratuit? %>
      <p class="text-danger">
        <i class="fas fa-exclamation-circle" title="La limite de la formule 'Libre' a été dépassée !"></i>
        Nombre de Factures : 
        <span class="float-end">
          <%= number_with_delimiter(@organisation.factures.count, delimiter: " ") %>
        </span>
        <br>
        <b>Limite de la formule libre et gratuite dépassée !</b> 
        <br>
        <%= link_to "Merci de nous contacter pour changer de formule.", "https://www.philnoug.com/contact" %>
      </p>
    <% else %>
      <p>
        Nombre de Factures : 
        <span class="float-end">
          <%= number_with_delimiter(@organisation.factures.count, delimiter: " ") %>
        </span>
      </p>
    <% end %>
  </div>

  <div class="col px-5 mx-3">
    <p>
      Total des Factures : 
      <span class="float-end">
        <%= number_to_currency(montant_total_factures = @organisation.factures.sum(:montant)) %>
      </span>
    </p>
    <p>
      Total des Paiements : 
      <span class="float-end">
        <%= number_to_currency(montant_total_paiements = @organisation.paiements.sum(:montant)) %>
      </span>
    </p>
    <p>
      Balance : 
      <span class="float-end <%= 'text-danger' if (montant_total_factures - montant_total_paiements).negative? %>">
        <%= number_to_currency(montant_total_factures - montant_total_paiements) %>
      </span>
    </p>
  </div>
</div>

<div class="shadow-sm mx-auto my-4 p-5">
  <div class="h4 px-2 fw-light">Facturation des 12 derniers mois</div>
  <canvas class="p-10" id="chartBar"></canvas>
</div>

<!-- Required chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<!-- Chart bar -->
<script>
  const dataBarChart = {
    labels: <%= @results.keys.to_json.html_safe %>,
    datasets: [
      {
        label: "Total facturé (€)",
        backgroundColor: "hsl(252, 82.9%, 67.8%)",
        borderColor: "hsl(252, 82.9%, 67.8%)",
        data: <%= @results.values.to_json.html_safe %>,
      },
    ],
  };

  const configBarChart = {
    type: "bar",
    data: dataBarChart,
    options: {},
  };

  var chartBar = new Chart(
    document.getElementById("chartBar"),
    configBarChart
  );
</script>

app/views/admin/envoyer_factures.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light"><%= fa_icon 'calendar-day' %> Envoyer les factures</h2>
</div>

<p>
  <h4>Permet l'envoi automatique, par email, de toutes les factures en état 'vérifiée'.</h4>
  <small>L'adresse du destinataire est celle du premier contact du compte.</small>
</p>
<br />

<%= bootstrap_form_with(url: "envoyer_factures_do", method: :post, local: true) do |form| %>
  <%= form.check_box :envoyer, {custom: :switch, label: "Envoyer les emails ? (Décoché = Visualisation seulement. Ne fait rien de définitif :)"} %>  
  <br /><br />
  <%= form.submit "Lancer", class: "btn btn-outline-success", 'data-turbo': false %>
<% end %>

app/views/admin/envoyer_factures_do.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light"><%= fa_icon 'calendar-day' %> Envoyer factures</h2>
</div>

<pre>
  <%= simple_format(@stdout_stream) %>
</pre>

app/views/admin/import.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light"><%= fa_icon 'file-import' %> Importer données XLS</h2>
</div>

<p>
    <p>
        <h4>Pour importer les données, votre fichier doit être au format Excel 97-2003 (.xls)<br /> et contenir les colonnes suivantes :</h4>
        <%= Compte.xls_headers.join(', ') %>
    </p>

    <p>
        Exemple de fichier : <%= link_to "Fichier.xls", admin_exemple_fichier_import_xls_url %>
    </p>

    <p>
        <i>
            Ne permet que d'importer des données nouvelles. 
            Pour mettre à jour des données existantes, supprimer l'enregistrement pour qu'il soit recréé avec les nouvelles données.
        </i>
    </p>
</p>

<%= bootstrap_form_with(url: "import_do", method: :post, local: true) do |form| %>

    <div class="form-group col-sm-6">
        <%= form.file_field :file, {accept: '.xls', required: true, label: 'Fichier à importer'} %>
        <%= form.check_box :enregistrer, {custom: :switch, label: "Enregistrer les changements ? (non=Visualisation seulement)"} %>  
    </div>
    <br />

    <%= form.submit "Importer", class: "btn btn-outline-success", 'data-turbo': false %>
<% end %>

<script type="text/javascript">
    // Workaround for displaying selected file
    $("input[type=file]").change(function () {
        var fieldVal = $(this).val();

        // Change the node's value by removing the fake path (Chrome)
        fieldVal = fieldVal.replace("C:\\fakepath\\", "");

        if (fieldVal != undefined || fieldVal != "") {
            $(this).next(".custom-file-label").attr('data-content', fieldVal);
            $(this).next(".custom-file-label").text(fieldVal);
        }
    });
</script>

app/views/admin/import_do.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light"><%= fa_icon 'file-import' %> Importer données XLS</h2>
</div>

<pre>
    <% @messages.each do |msg| %>
        <p><%= msg %></p>
    <% end %>
</pre>

app/views/admin/index.html.erb
<div class="pb-2 mt-4 mb-4 border-bottom">
  <h2 class="fw-light d-inline"><%= fa_icon 'users-cog', class: 'text-success' %> Administration</h2>
  <%= link_to guide_path(anchor: "administration") do %>
    <%= fa_icon 'question-circle', type: :regular, title: "Ouvrir l'aide", class: 'text-muted mx-2' %>
  <% end %>
</div>
<br />

<div class="row" style="gap: 2rem;">
  <div class="col">
    <ul class="list-group">
      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'city', class: "col-sm-2" %> 
          <%= link_to organisation_url(current_user.organisation), title: "Organisation, Structures, Vacances", class: "text-muted text-decoration-none" do %>Organisation<% end %>
        </h4>
      </li>

      <li class="list-group-item"></li>

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'user-friends', class: "col-sm-2" %>
          <%= link_to users_admin_index_path, class: "text-muted text-decoration-none" do %>
            Utilisateurs / Portail Parents
          <% end %>
        </h4>
      </li>

      <li class="list-group-item"></li>

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'euro-sign', class: "col-sm-2"  %>
          <%= link_to admin_tarifs_url, title: "Tarifs, Types de tarifs et de Prestations", class: "text-muted text-decoration-none" do %>
            Prestations et Tarifs
          <% end %>
        </h4>
      </li>

    </ul>  
  </div>

  <div class="col">
    <ul class="list-group">

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'calendar-day', class: "col-sm-1" %>
          <%= link_to 'Comptabilisation prestations', admin_ajout_prestations_path, class: "text-muted text-decoration-none" %>
        </h4>
      </li>

      <li class="list-group-item"></li>

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'calendar-day', class: "col-sm-1" %>
          <%= link_to 'Facturation prestations', admin_ajout_factures_path, class: "text-muted text-decoration-none" %>
        </h4>
      </li>

      <li class="list-group-item"></li>

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'paper-plane', class: "col-sm-1" %>
          <%= link_to 'Envoyer les factures', admin_envoyer_factures_path, class: "text-muted text-decoration-none" %>
        </h4>
      </li>

      <li class="list-group-item"></li>

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'envelope', class: "col-sm-1" %>
          <%= link_to 'Messages (contestations)', messages_path, class: "text-muted text-decoration-none", title:"Journal d'activité des envois de courriels" %>
          <% if @unread_messages > 0 %>
            <span class="badge text-bg-danger rounded-pill ms-2"style="font-weight: 900"><%= @unread_messages %></span>
          <% end %>
        </h4>
      </li>

      <li class="list-group-item"></li>

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'mail-bulk', class: "col-sm-1" %>
          <%= link_to 'Mail Logs', mail_logs_path, class: "text-muted text-decoration-none", title:"Journal d'activité des envois de courriels" %>
        </h4>
      </li>

    </ul>
  </div>

  <div class="col">
    <ul class="list-group">

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'search', class: "col-sm-2" %>
          <%= link_to 'Audit des modifications', admin_audit_path, class: "text-muted text-decoration-none" %>
        </h4>
      </li>

      <li class="list-group-item"></li>

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'file-import', class: "col-sm-2" %>
          <%= link_to 'Importer', admin_import_path, class: "text-muted text-decoration-none" %>
        </h4>
      </li>

      <li class="list-group-item"></li>

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'comment-dots', class: "col-sm-2" %>
          <%= link_to 'Messages de factures', facture_messages_path, title: "Afficher en bas de vos factures et dans l'e-mail d'accompagnement" ,class: "text-muted text-decoration-none" %>
        </h4>
      </li>

      <li class="list-group-item"></li>
      <li class="list-group-item text-danger text-center fw-bold">Zone dangereuse</li>

      <li class="list-group-item">
        <h4 class="fw-light my-2">
          <%= fa_icon 'skull-crossbones', class: "col-sm-2" %>
          <%= link_to "Supprimer organisation", suppression_organisation_organisation_path(current_user.organisation), class: "text-muted text-decoration-none" %>
        </h4>
      </li>

    </ul>
  </div>

</div>

app/views/admin/stats.html.erb
<h1 class="font-bold my-4">Admin</h1>

Total Facturé : <%= number_to_currency(Facture.sum(:montant), precision: 0) %>

<div class='overflow-x-auto mb-4'>
  <table class='table'>
    <thead>
      <tr>
        <th>Organisation</th>
        <th>User email</th>
        <th>Dernière Connexion</th>
        <th>Nbr</th>
        <th>Familles</th>
        <th>Enfants</th>
        <th>Factures</th>
        <th>Total Facturé</th>
        <th>Modifié le</th>
        <th>Créé le</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @organisations.uniq.each do |organisation| %>
        <% organisation.users.each do |user| %>
          <tr>
            <td><%= organisation.nom %></td>
            <td><%= user.email %> (<%= user.role %>)</td>
            <td><%= time_ago_in_words user.last_sign_in_at if user.sign_in_count.positive? %></td>
            <td class=" <%= user.sign_in_count > 1 ? 'text-info font-weight-bold' : ''  %>"><%= user.sign_in_count %></td>
            <% if organisation.users.first == user %>
              <td class=<%= 'text-info' if organisation.comptes.count > 1 %>><%= organisation.comptes.count %></td>
              <td><%= organisation.enfants.count %></td>
              <td class=<%= 'text-danger' if organisation.factures.count >= 1000 %>><%= organisation.factures.count %></td>
              <td class="text-end"><%= number_to_currency(organisation.factures.sum(:montant), precision: 0) %></td>
              <td><%= time_ago_in_words user.updated_at %></td>
              <td><%= time_ago_in_words user.created_at %></td>
              <td>
                <%= form_with(url: suppression_organisation_do_organisation_path(id: organisation.slug)) do |form| %>
                  <%= form.submit "[X]", class: "btn btn-outline-danger" %>
                <% end %>
              </td>
            <% else %>
              <td colspan=5></td>
              <td><%= time_ago_in_words user.updated_at %></td>
              <td></td>
            <% end %>
            
          </tr>
        <% end %>
        <tr></tr>
      <% end %>
    </tbody>
  </table>
</div>

<span><%= page_entries_info @organisations, entry_name: 'user' %></span>
<%= paginate @organisations, theme: 'twitter-bootstrap-4' %>

app/views/admin/tarifs.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light d-inline"><%= fa_icon 'euro-sign' %> Prestations et Tarifs</h2>
  <%= link_to guide_path(anchor: "tarifs") do %>
    <%= fa_icon 'question-circle', type: :regular, title: "Ouvrir l'aide", class: 'text-muted mx-2' %>
  <% end %>
</div>
<p>
  <small class="text-muted">
  Pour ajouter une prestation de 'Garderie' au Tarif 'Général' : 
  il faut ajouter un type de prestation 'Garderie' 
  et créer un Tarif qui associe 'Garderie' + 'Général' + 'Prix de la prestation (€)'.
  </small>
</p>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
      <th>Nom du type de Tarif</th>
      <th>Nom du type de Prestation</th>
      <th>Prix</th>  
      <th></th>
      </tr>
    </thead>

    <% @organisation.tarifs.each do | tarif | %>
      <tr>
      <td><%= tarif.tarif_type.nom %></td>
      <td><%= tarif.prestation_type.nom %></td>
      <td><%= number_to_currency(tarif.prix, unit: '€', precision: 2, format: "%n %u") %></td>
      <td>
        <% if policy(tarif).destroy? %>
          <%= button_to tarif, method: :delete, 'data-turbo-confirm': 'Êtes-vous bien certain.e ???', class:'btn btn-sm' do %>
            <%= fa_icon 'trash-alt', class: 'text-danger' %>
          <% end %>
        <% end %>
      </td>
      </tr>
    <% end %>
  </table>
</div>

<% if policy(Tarif).new? %>
  <%= link_to new_tarif_path(organisation_id: @organisation), data: {'bs-toggle': "modal", 'bs-target': "#myModalTarif" }, class: "btn  btn-outline-primary mb-5" do %>
    <%= fa_icon 'plus-circle' %> Créer un nouveau tarif
  <% end %>
<% end %>

<div class="row">

  <div class="col">
    <h3 class="fw-light">Types de prestations</h3>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Nom</th>
            <th></th>
          </tr>
        </thead>
        <% @organisation.prestation_types.each do |prestation_type| %>
          <tr>
            <td><%= link_to prestation_type.nom.humanize, edit_prestation_type_path(prestation_type) %></td>
            <td class="text-end col-sm-1">
              <% if policy(prestation_type).destroy? %>
                <%= button_to prestation_type, method: :delete, 'data-turbo-confirm': 'Êtes-vous bien certain.e ???', class:'btn btn-sm p-0' do %>
                  <%= fa_icon 'trash-alt', class:'text-danger fs-6' %>
                <% end %>
              <% else %>
                <%= fa_icon 'trash-alt', class:'text-muted', title: "Pas supprimable : il y a des données liées dans Réservations, Prestations, ou Tarifs" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>

    <% if policy(PrestationType).new? %>
      <%= link_to new_prestation_type_path(organisation_id: @organisation), 
          data: {'bs-toggle': "modal", 'bs-target': "#myModalTypePresta" }, class: "btn btn-outline-primary" do %>
        <%= fa_icon 'plus-circle' %> Ajouter un type de prestation
      <% end %>
    <% end %>
  </div>

  <div class="col">
    <h3 class="fw-light">Types de tarifs</h3>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Nom</th>
            <th></th>
          </tr>
        </thead>
        <% @organisation.tarif_types.each do |tarif_type| %>
          <tr>
            <td><%= link_to tarif_type.nom, edit_tarif_type_path(tarif_type) %></td>
            <td class="text-end col-sm-1">
              <% if policy(tarif_type).destroy? %>
                <%= button_to tarif_type, method: :delete, 'data-turbo-confirm': 'Êtes-vous bien certain.e ???', class:'btn btn-sm' do %>
                  <%= fa_icon 'trash-alt', class: 'text-danger' %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <% if policy(TarifType).new? %>
      <%= link_to new_tarif_type_path(organisation_id: @organisation), data: {'bs-toggle': "modal", 'bs-target': "#myModalTypeTarif" }, class: "btn  btn-outline-primary" do %>
      <%= fa_icon 'plus-circle' %> Ajouter un type de tarif
      <% end %>
    <% end %>
  </div>

</div>
<br />

<div class="modal fade" id="myModalTypeTarif">
  <div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">

    <!-- Modal Header -->
    <div class="modal-header">
    <h4 class="modal-title">Nouveau Type de Tarif</h4>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <!-- Modal body -->
    <div class="modal-body">
    <%= render 'tarif_types/form', tarif_type: TarifType.new(organisation_id: @organisation.id) %>
    </div>
  </div>
  </div>
</div>

<div class="modal fade" id="myModalTypePresta">
  <div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">

    <!-- Modal Header -->
    <div class="modal-header">
    <h4 class="modal-title">Nouveau Type de Prestation</h4>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <!-- Modal body -->
    <div class="modal-body">
    <%= render 'prestation_types/form', prestation_type: PrestationType.new(organisation_id: @organisation.id) %>
    </div>
  </div>
  </div>
</div>

<div class="modal fade" id="myModalTarif">
  <div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">

    <!-- Modal Header -->
    <div class="modal-header">
    <h4 class="modal-title">Nouveau Tarif</h4>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <!-- Modal body -->
    <div class="modal-body">
    <%= render 'tarifs/form', tarif: Tarif.new %>
    </div>
  </div>
  </div>
</div>