config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations',  omniauth_callbacks: 'users/omniauth_callbacks'  }

  resources :users_admin, controller: 'users'

  resources :comptes do 
    get :balance
  end
  
  get 'moncompte/index'
  get 'moncompte/releve_compte'
  get 'moncompte/factures'
  get 'moncompte/absences'
  get 'moncompte/enfants'
  get 'moncompte/reservations'
  get 'moncompte/contacts'

  resources :factures do
    collection do
      post :action
    end
  end

  resources :enfants do
    collection do
      post :action
      post :action_execute
    end
  end

  resources :reservations, except: %i[ show create update ] do
    collection do
      post :action
      post :create_visiteur
    end
  end

  resources :prestations do
    collection do
      post :action
    end
  end
  resources :tarifs, except: %i[ index ]
  resources :absences
  resources :tarif_types, except: %i[ index show ]
  resources :prestation_types, except: %i[ index show ]
  resources :structures, except: %i[ index new create ]
  resources :organisations do
    member do
      get :suppression_organisation
      post :suppression_organisation_do
    end
  end
  resources :paiements
  resources :facture_messages
  resources :messages do
    member do
      get :traiter
      get :archiver
    end
  end
  resources :vacances, except: %i[ index ]
  resources :mail_logs, only: %i[ index show ]
  resources :pointages, only: %i[ index edit update ] do
    collection do
      post :action
    end
  end

  namespace :admin do
    get :index
    get :ajout_prestations
    get :ajout_factures
    get :tarifs
    get :audit
    get :import
    get :exemple_fichier_import_xls
    get :envoyer_factures
    get :mode_demonstration
    get :dashboard
    get :stats

    post :ajout_prestations_do
    post :ajout_factures_do
    post :import_do
    post :envoyer_factures_do
  end

  controller :pages do
    get :accueil, to: 'pages#home'
    get :guide, to: 'pages#guide'
    get :actualites, to: 'pages#actualites'
    get :confidentialite, to: 'pages#confidentialite'
    post :conditions_generales_de_vente, to: 'pages#conditions_generales_de_vente'
  end

  root 'pages#accueil'

end

app/controllers/moncompte_controller.rb
class MoncompteController < ApplicationController

  def index
    # Vérifie que le compte est autorisé à se connecter
    @compte = Contact.find_by(email: current_user.email).compte
    authorize @compte

    # Prépare les totaux et les lignes du relevé de compte
    @total_factures = @compte.factures.sum(:montant)
    @total_paiements = @compte.paiements.sum(:montant)
    @solde = @total_paiements - @total_factures
    @releve = @compte.balance

    @enfants_count = @compte.enfants.count
    @réservations_count = @compte.reservations.count
    @factures_count = @compte.factures.count
    @absences_count = @compte.absences.count
    @contacts_count = @compte.contacts.count

    @total_alg = @total_sp = @total_vege = 0
  end

  def releve_compte
    @compte = Contact.find_by(email: current_user.email).compte
    @releve = @compte.balance
  end

  def factures
    @compte = Contact.find_by(email: current_user.email).compte
    @factures = @compte.factures
  end

  def absences
    @compte = Contact.find_by(email: current_user.email).compte
    @absences = @compte.absences
  end

  def enfants
    @compte = Contact.find_by(email: current_user.email).compte
    @enfants = @compte.enfants
  end
  
  def reservations
    @compte = Contact.find_by(email: current_user.email).compte
    @enfants = @compte.enfants
  end

  def contacts
    @compte = Contact.find_by(email: current_user.email).compte
    @contacts = @compte.contacts
  end

end

app/views/moncompte/_absence.html+phone.erb
<div class="container gap-2">
  <div class="row">
    <%= l absence.début %>
    au <%= l absence.fin %>
  </div>
</div>
<hr>

app/views/moncompte/_balance.html+phone.erb
<div class="container gap-2">
    <div class="row">
        <div class="col-3"><%= l ligne[:date], format: :short %></div>
        <% if ligne[:type] == "Facture" %>
            <div class="col">Facture <%= ligne[:ref] %></div>
            <div class="col-3 text-end">-<%= number_to_currency(ligne[:mnt], unit:'€') %></div>
        <% else %>
            <div class="col"><%= ligne[:ref] %></div>
            <div class="col-3 text-end"><%= number_to_currency(ligne[:mnt], unit:'€') %></div>
        <% end %>
    </div>
</div>
<hr>

app/views/moncompte/_contact.html+phone.erb
<div class="container gap-2">
  <div class="row">
    <%= contact.nom %>
    <%= contact.email %>
  </div>
  <div class="row">
    <%= contact.fixe %>
    <%= contact.portable %>
  </div>
  <div class="row">
    <%= "À prévenir en cas d'urgence" if contact.prevenir %>
  </div>
</div>
<hr>

app/views/moncompte/_enfant.html+phone.erb
<div class="container gap-2">
  <div class="row">
    <%= enfant.prénom %>
    <%= enfant.nom %>
    (<%= time_ago_in_words(enfant.date_naissance) if enfant.date_naissance %>)
  </div>
  <div class="row">
    <%= enfant.classroom.nom %>
    <%= "Végétarien" if enfant.menu_vege %>
    <%= "Sans porc" if enfant.menu_sp %>
    <%= "Allergie" if enfant.menu_all %>
    <%= enfant.allergenes %>
  </div>
</div>
<hr>

app/views/moncompte/_facture.html+phone.erb
<div class="container gap-2">
  <div class="row">
    <div class="col"><%= facture.réf %></div>
    <div class="col-4 text-end"><%= number_to_currency(facture.montant, unit: '€', precision: 2, format: '%n %u') %></div>
    <div class="col-2 text-end">
      <%= link_to facture_url(facture, format: :pdf), target: '_blank', title: "Voir la facture en PDF", class: 'btn btn-sm' do %>
        <i class="fas fa-2x fa-file-pdf text-danger"></i>
      <% end %>
    </div>
  </div>
</div>
<hr>

app/views/moncompte/_reservation.html+phone.erb
<div class="container gap-2">
  <div class="row">
    <%= l reservation.début %>
    au <%= l reservation.fin %>
    <%= reservation.prestation_type.nom %>
    <%# enfant.nom %>
    <%# time_ago_in_words(enfant.date_naissance) if enfant.date_naissance %>
  </div>
  <div class="row">
    <%# enfant.classroom.nom %>
    <%# "Végétarien" if enfant.menu_vege %>
    <%# "Sans porc" if enfant.menu_sp %>
    <%# "Allergie" if enfant.menu_all %>
    <%# enfant.allergenes %>
  </div>
</div>
<hr>

app/views/moncompte/_reservation.html.erb
<%= bootstrap_form_with(model: reservation, url: create_visiteur_reservations_path) do |form| %>

  <p>
    <h2>
      <%= reservation.try(:enfant).try(:nom_et_prénom) %>
    </h2>
  </p>

  <%= form.hidden_field :enfant_id %>

  <%= form.select :enfant_id, options_from_collection_for_select(@compte.enfants, 'id', 'prénom', reservation.enfant_id), { label: 'Enfant', wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, { class: "selectpicker" } %>

  <%= form.select :prestation_type_id, options_from_collection_for_select(@compte.organisation.prestation_types, 'id', 'nom', reservation.prestation_type_id), { label: 'Prestation', wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, { class: "selectpicker" } %>

  <div class="form-inline">
    <%= form.text_field :début, label: 'Du :', class: "form-control", type: "date" %>
    <%= form.text_field :fin, label: 'Au :', class: "form-control", type: "date" %>
  </div>
  
  <div class="row">
    <div class="col"><%= form.text_field :lundi %></div>
    <div class="col"><%= form.text_field :mardi %></div>
    <div class="col"><%= form.text_field :mercredi %></div>
    <div class="col"><%= form.text_field :jeudi %></div>
  </div>
  <div class="row">
    <div class="col-3"><%= form.text_field :vendredi %></div>
    <div class="col-3"><%= form.text_field :samedi %></div>
    <div class="col-3"><%= form.text_field :dimanche %></div>
  </div>

  <div class="custom-control">
    <%= form.check_box :matin, custom: :switch %>
    <%= form.check_box :midi, custom: :switch %>
    <%= form.check_box :soir, custom: :switch %>
  </div>
  <br />

  <%= form.submit "Enregistrer", class: "btn btn-outline-success" %>

<% end %>

app/views/moncompte/absences.html.erb
<%= turbo_frame_tag "main_frame" do %>
  <section class="mt-4">
    <h4>Absences</h4>
    <% @absences.each do |absence| %>
      <%= render partial: 'absence', locals: {absence: absence} %>
    <% end %>
  </section>
<% end %>

app/views/moncompte/contacts.html.erb
<%= turbo_frame_tag "main_frame" do %>
  <section class="mt-4">
    <h4>Contacts</h4>
    <% @contacts.each do |contact| %>
      <%= render partial: 'contact', locals: {contact: contact} %>
    <% end %>
  </section>
<% end %>

app/views/moncompte/enfants.html.erb
<%= turbo_frame_tag "main_frame" do %>
  <section class="mt-4">
    <h4>Mes enfants</h4>

    <% @enfants.each do |enfant| %>
      <%= render partial: 'enfant', locals: {enfant: enfant} %>
    <% end %>
  </section>
<% end %>

app/views/moncompte/factures.html.erb
<%= turbo_frame_tag "main_frame" do %>
  <section class="mt-4">
    <h4>Factures</h4>
    <% @factures.each do |facture| %>
      <%= render partial: 'facture', locals: {facture: facture} %>
    <% end %>
  </section>
<% end %>

app/views/moncompte/index.html+phone.erb
<div class="container">
  <div class="row mb-3 gap-3">
    <div class="col pf-btn border border-primary rounded gap-3 shadow-sm p-2">
      <%= link_to moncompte_enfants_path, data: { turbo_frame: "main_frame" }, class:'text-decoration-none text-muted' do %>
        <div class="col container gap-2">
          <div class="row">
            <div class="col px-0 text-center">
              <%= fa_icon 'child', class: 'text-primary', size: '2x' %>
            </div>
            <div class="col-9 px-0 my-auto">
              <p class="mb-0"><%= "Enfant".pluralize(@enfants_count) %> (<%= @enfants_count %>)</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col pf-btn border border-success rounded gap-3 shadow-sm p-2">
      <%= link_to moncompte_contacts_path, data: { turbo_frame: "main_frame" }, class:'text-decoration-none text-muted' do %>
        <div class="col container gap-2">
          <div class="row">
            <div class="col px-0 text-center">
              <%= fa_icon 'phone', class: 'text-success', size: '2x' %>
            </div>
            <div class="col-9 px-0 my-auto">
              <p class="mb-0 flex-fill"><%= "Contact".pluralize(@contacts_count) %> (<%= @contacts_count %>)</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row mb-3 gap-3">
    <div class="col pf-btn border border-warning rounded gap-3 shadow-sm p-2">
      <%= link_to moncompte_reservations_path, data: { turbo_frame: "main_frame" }, class:'text-decoration-none text-muted' do %>
        <div class="col container gap-2">
          <div class="row">
            <div class="col px-0 text-center">
              <%= fa_icon 'calendar-alt', class: 'text-warning', size: '2x' %>
            </div>
            <div class="col-9 px-0 my-auto">
              <p class="mb-0">Réservations</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col pf-btn border border-danger rounded gap-3 shadow-sm p-2">
      <div class="col container gap-2">
        <%= link_to moncompte_absences_path, data: { turbo_frame: "main_frame" }, class:'text-decoration-none text-muted' do %>
          <div class="row">
            <div class="col px-0 text-center">
              <%= fa_icon 'calendar-times', class: 'text-danger', size: '2x' %>
            </div>
            <div class="col-9 px-0 my-auto">
              <p class="mb-0"><%= "Absence".pluralize(@absences_count) %> (<%= @absences_count %>)</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row mb-3 gap-3">
    <div class="col pf-btn border border-info rounded gap-3 shadow-sm p-2">
      <div class="col container gap-2">
        <%= link_to moncompte_factures_path, data: { turbo_frame: "main_frame" }, class:'text-decoration-none text-muted' do %>
          <div class="row">
            <div class="col px-0 text-center">
              <%= fa_icon 'file-invoice', class: 'text-info', size: '2x' %>
            </div>
            <div class="col-9 px-0 my-auto">
              <p class="mb-0"><%= "Facture".pluralize(@factures_count) %> (<%= @factures_count %>)</p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col pf-btn border border-muted rounded gap-3 shadow-sm p-2">
      <div class="col container gap-2">
        <%= link_to moncompte_releve_compte_path, data: { turbo_frame: "main_frame" }, class:'text-decoration-none text-muted' do %>
          <div class="row">
            <div class="col px-0 text-center">
              <%= fa_icon 'euro-sign', class:'text-muted', size: '2x' %>
            </div>
            <div class="col-9 px-0 my-auto">
              <p class="mb-0">
                <span class="<%= 'text-danger' if @solde.negative? %>">
                  <%= number_to_currency(@solde, unit: '€', precision: 2, format: "%n %u") %>
                </span>
              </p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= turbo_frame_tag "main_frame" do %>
  <p class="fs-1 text-center mt-5">Bienvenue !</p>
<% end %>

app/views/moncompte/index.html.erb
<div class="card mb-5">
  <div class="card-header">
    <h2 class="fw-light"><%= fa_icon 'user' %> <%= @compte.nom %></h2>
  </div>

  <div class="card-body">
    <%= render partial: 'comptes/compte-card' %>

    <div class="card mt-3">
      <div class="card-body">
        <h3><%= fa_icon 'child', class: 'text-primary' %> Enfants</h3>
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-sm">
            <thead>
              <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Date naissance</th>
                <th>Classe</th>
                <th>Menu Végé?</th>
                <th>Menu SP?</th>
                <th>Menu ALLERGIE?</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <% @compte.enfants.each do |enfant| %>
              <tr>
                <td><%= enfant.nom %></td>
                <td><%= enfant.prénom %></td>
                <td><%= l(enfant.date_naissance) if enfant.date_naissance %></td>
                <td><%= enfant.classroom.nom %></td>
                <td class="text-center"><%= fa_icon 'check' if enfant.menu_vege %></i></td>
                <td class="text-center"><%= fa_icon 'check' if enfant.menu_sp %></i></td>
                <td class="text-center"><%= fa_icon 'check' if enfant.menu_all %></i></td>
                <td>
                  <% if policy(enfant).edit? %>
                    <%= link_to edit_enfant_path(enfant) do %>
                      <%= fa_icon 'edit' %>
                    <% end %>
                  <% end %>
                </td>
                <td>
                  <% if policy(enfant).destroy? %>
                    <%= button_to enfant, method: :delete, 'data-turbo-confirm': 'Êtes-vous bien certain.e ???', class:'btn btn-sm' do %>
                        <%= fa_icon 'trash-alt', class: 'text-danger' %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>

          </table>
        </div>
      </div>
    </div>
  

    <div class="card">
      <div class="card-body">
        <h3><%= fa_icon 'calendar-alt', class: 'text-warning' %> Réservations</h3>
        
        <% if @compte.reservations.any? %>
          <div class="table-responsive">
            <table class="table table-bordered table-hover table-sm">
              <thead>
                <tr>
                  <th>Structure</th>
                  <th>Classe</th>
                  <th>Enfant</th>
                  <th>ALG?</th>
                  <th>Végé?</th>
                  <th>SP?</th>
                  <th>Prestation</th>
                  <th>Début</th>
                  <th>Fin</th>
                  <th>Etat</th>
                  <th>Lun</th>
                  <th>Mar</th>
                  <th>Mer</th>
                  <th>Jeu</th>
                  <th>Ven</th>
                  <th>Matin</th>
                  <th>Midi</th>
                  <th>Soir</th>
                  <th>HScol?</th>
                </tr>
              </thead>

              <tbody>
                <%= render @compte.reservations.includes(:enfant) %>
              </tbody>
            </table>
          </div>
        <% else %>
          <p>
            Aucune réservation pour l'instant...
          </p>
        <% end %>
      </div>

      <div class="card-footer">
        <%= link_to new_reservation_path, data: {'bs-toggle': "modal", 'bs-target': "#myModalTarif" }, class: 'btn btn-outline-primary' do %>
          <%= fa_icon 'plus-circle', text: ' Ajouter une réservation' %>
        <% end %>
      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <h3><%= fa_icon 'balance-scale' %> Relevé de compte</h3>

        <div class="table-responsive">
          <table class="table table-hover table-bordered table-sm">
            <thead>
              <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Référence</th>
                <th class="text-end">Débit</th>
                <th class="text-end">Crédit</th>
                <th class="text-end">Solde</th>
              </tr>
            </thead>

            <tbody>
              <% @releve.each do |ligne| %>
                <%= render partial: 'comptes/balance', locals: {ligne: ligne} %>
              <% end %>
            </tbody>

            <tfoot>
              <tr>
                <th><%= l Date.today %></th>
                <th>SOLDE</th>
                <th></th>
                <th class="text-end"><%= number_to_currency(@debit, unit:'€') %></th>
                <th class="text-end"><%= number_to_currency(@credit, unit:'€') %></th>
                <th class="text-end"><%= number_to_currency(@solde, unit:'€') %></th>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
      <div class="card-footer">
        <% if policy(Paiement).new? %>
          <%= link_to new_paiement_path, class: 'btn btn-outline-primary' do %>
            <%= fa_icon 'plus-circle', text: ' Effectuer un paiement' %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="modal fade" id="myModalNewPaiement">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title">Nouveau Paiement</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>

          <!-- Modal body -->
          <div class="modal-body">
            <%= render 'paiements/form', paiement: Paiement.new(compte_id: @compte.id) %>
          </div>
        </div>
      </div>
    </div>
    <br>

    <div class="modal fade" id="myModalTarif">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title">Nouvelle réservation</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>

          <!-- Modal body -->
          <div class="modal-body">
            <%= render 'reservation', reservation: @compte.reservations.new %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/moncompte/releve_compte.html.erb
<%= turbo_frame_tag "main_frame" do %>
  <section class="mt-4">
    <h4>Relevé de compte</h4>

    <% @releve.each do |ligne| %>
      <%= render partial: 'balance', locals: {ligne: ligne} %>
    <% end %>
  </section>
<% end %>